name: Upload GitHub file to Confluence
permissions:
  contents: read # required to check out the code from the repo
  id-token: write # required to use OIDC authentication

on:
  workflow_dispatch:

env:
  CONF_REPO: <add-repo-name-here>
  CONF_REPO_ORG: FlutterInt
  REPO_DATA_PATH: .github/workflows/upload_github_files_to_confluence.yml
  CONFLUENCE_REST_API: https://confluence.pyrsoftware.ca/confluence/rest/api
  CONFLUENCE_PAGE_ID: 891098311

jobs:
  Build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
    
      - name: Uploads file to Confluence
        uses: markdown-confluence/publish@v1
        with:
          from: '.github/workflows/upload_github_files_to_confluence.yaml'
          to: 891098311
          cloud: confluence.pyrsoftware.ca/confluence/rest/api
          user: ${{ secrets.CONFLUENCE_EMAIL }}
          token: ${{ secrets.CONFLUENCE_TOKEN }}
